-- MySQL Script generated by MySQL Workbench
-- Sun Oct 27 19:39:17 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema university_timetable
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `university_timetable` DEFAULT CHARACTER SET utf8 ;
USE `university_timetable` ;

-- -----------------------------------------------------
-- Table `university_timetable`.`Courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university_timetable`.`Courses` (
  `course_id` VARCHAR(3) NOT NULL,
  `course_name` VARCHAR(45) NULL,
  PRIMARY KEY (`course_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `university_timetable`.`Modules`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university_timetable`.`Modules` (
  `module_id` VARCHAR(3) NOT NULL,
  `module_name` VARCHAR(45) NULL,
  `course_id` VARCHAR(3) NULL,
  PRIMARY KEY (`module_id`),
  CONSTRAINT `FK_course_id`
    FOREIGN KEY (`course_id`)
    REFERENCES `university_timetable`.`Courses` (`course_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `university_timetable`.`Classes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university_timetable`.`Classes` (
  `class_id` VARCHAR(3) NOT NULL,
  `module_id` VARCHAR(3) NULL,
  PRIMARY KEY (`class_id`),
  CONSTRAINT `FK_classes_module_id`
    FOREIGN KEY (`module_id`)
    REFERENCES `university_timetable`.`Modules` (`module_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `university_timetable`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university_timetable`.`Users` (
  `user_id` VARCHAR(3) NOT NULL,
  `name` VARCHAR(45) NULL,
  `dob` DATE NULL,
  `role` VARCHAR(45) NULL,
  `gender` VARCHAR(45) NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `university_timetable`.`Students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university_timetable`.`Students` (
  `student_id` VARCHAR(3) NOT NULL,
  `course_id` VARCHAR(3) NULL,
  `user_id` VARCHAR(3) NULL,
  PRIMARY KEY (`student_id`),
  CONSTRAINT `FK_students_course_id`
    FOREIGN KEY (`course_id`)
    REFERENCES `university_timetable`.`Courses` (`course_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_students_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `university_timetable`.`Users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `university_timetable`.`ModuleEnrolements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university_timetable`.`ModuleEnrolements` (
  `module_enrolement_id` VARCHAR(3) NOT NULL,
  `student_id` VARCHAR(3) NULL,
  `module_id` VARCHAR(3) NULL,
  PRIMARY KEY (`module_enrolement_id`),
  CONSTRAINT `FK_module_enrolements_student_id`
    FOREIGN KEY (`student_id`)
    REFERENCES `university_timetable`.`Students` (`student_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_module_enrolements_module_id`
    FOREIGN KEY (`module_id`)
    REFERENCES `university_timetable`.`Modules` (`module_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `university_timetable`.`Teachers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university_timetable`.`Teachers` (
  `teacher_id` VARCHAR(3) NOT NULL,
  `user_id` VARCHAR(3) NULL,
  PRIMARY KEY (`teacher_id`),
  INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FK_teachers_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `university_timetable`.`Users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `university_timetable`.`TeachingQualifications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university_timetable`.`TeachingQualifications` (
  `teacher_qualification_id` VARCHAR(3) NOT NULL,
  `teacher_id` VARCHAR(3) NULL,
  `module_id` VARCHAR(3) NULL,
  PRIMARY KEY (`teacher_qualification_id`),
  INDEX `teacher_id_idx` (`teacher_id` ASC) VISIBLE,
  INDEX `module_id_idx` (`module_id` ASC) VISIBLE,
  CONSTRAINT `FK_teaching_qualifications_teacher_id`
    FOREIGN KEY (`teacher_id`)
    REFERENCES `university_timetable`.`Teachers` (`teacher_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_teaching_qualifications_module_id`
    FOREIGN KEY (`module_id`)
    REFERENCES `university_timetable`.`Modules` (`module_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `university_timetable`.`Events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university_timetable`.`Events` (
  `event_id` INT NOT NULL,
  `class_id` VARCHAR(45) NULL,
  `teacher_id` VARCHAR(3) NULL,
  `event_name` VARCHAR(45) NULL,
  `start_time` TIME NULL,
  `end_time` TIME NULL,
  `date` DATE NULL,
  PRIMARY KEY (`event_id`),
  INDEX `class_id_idx` (`class_id` ASC) VISIBLE,
  INDEX `teacher_id_idx` (`teacher_id` ASC) VISIBLE,
  CONSTRAINT `FK_events_class_id`
    FOREIGN KEY (`class_id`)
    REFERENCES `university_timetable`.`Classes` (`class_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_events_teacher_id`
    FOREIGN KEY (`teacher_id`)
    REFERENCES `university_timetable`.`Teachers` (`teacher_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `university_timetable`.`ClassEnrolements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university_timetable`.`ClassEnrolements` (
  `class_enrolement_id` VARCHAR(3) NOT NULL,
  `class_id` VARCHAR(3) NULL,
  `student_id` VARCHAR(3) NULL,
  PRIMARY KEY (`class_enrolement_id`),
  INDEX `class_id_idx` (`class_id` ASC) VISIBLE,
  INDEX `student_id_idx` (`student_id` ASC) VISIBLE,
  CONSTRAINT `FK_class_enrolements_class_id`
    FOREIGN KEY (`class_id`)
    REFERENCES `university_timetable`.`Classes` (`class_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_class_enrolements_student_id`
    FOREIGN KEY (`student_id`)
    REFERENCES `university_timetable`.`Students` (`student_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
